## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here
import numpy as np
import math

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [30]:
# okay numpy is great but... how would you inverse a matrix by hand?
def inverse_matrix(A):
    return ""
A = [0.6,-15,2,5,98]
B = [[2,2,4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]]

C = np.matmul(A,B)
print(C)

#The value of element c23​ gives an error of invalid index to scalar variable
#print(C[2][3])

# The number of columns in B is not equal to number of rows in A, so matrix multiplication is not possible.
#D = np.matmul(B,A) 
#print(D[2][3])




[-102.8  255.2  600.4]


![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [31]:
# Just answer using code --> easy stuff!

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 
A = [[3,0.6,4,-3],[-1.3,4,0,8.6],[7,0,-8,0.006]]
B = [[3,-5.76,45,0],[2,-2,1.3,9],[-9,0,0,0]]
C = [[0,1009,-66.7849,90],[0,5,4,-0.07],[-7.7,0,0,0]]
X = np.add(A,B)
D = np.subtract(X,C)
print(D)
print(D[2][3])

#The value of element D31​ gives an error of invalid index to scalar variable
#print(D[3][1])

[[ 6.000000e+00 -1.014160e+03  1.157849e+02 -9.300000e+01]
 [ 7.000000e-01 -3.000000e+00 -2.700000e+00  1.767000e+01]
 [ 5.700000e+00  0.000000e+00 -8.000000e+00  6.000000e-03]]
0.006


![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [33]:
# C will have 1 row and 3 columns
A = [0.6,-15,2,5,98]
B = [[2,2,4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]]
c = np.matmul(A,B)
print(c)
print(c[2])

# The value of c13 = 600.4


[-102.8  255.2  600.4]
600.4
