<!--NAVIGATION-->

<a href="https://colab.research.google.com/github/bpesquet/machine-learning-katas/blob/master/data/Tensor_Management.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open in Google Colaboratory"></a>


# Kata: Tensor Management

## Instructions

This is a self-correcting exercise generated by [nbgrader](https://github.com/jupyter/nbgrader). 

Complete the cells beginning with `# YOUR CODE HERE` and run the subsequent cells to check your code.

## Part 1: Tensor Basics

In [3]:
# Import NumPy
import numpy as np

### Question

Create a 2D tensor (a matrix) with dimensions (3,4) containing integer values of your choice. Store this tensor in a variable named `x`.

In [22]:
# YOUR CODE HERE
x = np.random.randint(12,size = (3,4))

array([[ 8,  1,  1,  0],
       [ 8, 10,  2,  1],
       [ 8,  8,  5,  7]])

In [7]:
print(x)
# Assert dimensions
assert x.ndim == 2
assert x.shape == (3, 4)
# Assert data type 
assert issubclass(x.dtype.type, np.integer)

[[ 6  2  5  2]
 [ 4  7  7  2]
 [10  0  4  6]]


### Question

Update the shape of the previous tensor so that it has dimensions (6,2).

In [24]:
# YOUR CODE HERE
x = x.reshape((6,2))

In [26]:
print(x)
# Assert tensor dimensions
assert x.ndim == 2
assert x.shape == (6, 2)

[[ 8  1]
 [ 1  0]
 [ 8 10]
 [ 2  1]
 [ 8  8]
 [ 5  7]]


### Question

Change the type of the previous tensor values to `float32`.

In [29]:
# YOUR CODE HERE
#x = np.random.random((6,2))
x = x.astype(float)

In [30]:
print(x)
# Assert data type
assert issubclass(x.dtype.type, np.floating)

[[ 8.  1.]
 [ 1.  0.]
 [ 8. 10.]
 [ 2.  1.]
 [ 8.  8.]
 [ 5.  7.]]


### Question

Normalize the previous tensor so that it has a mean of 0 and a standard deviation of 1 on its first axis.

In [40]:
# YOUR CODE HERE
print(x)
x_mean = x.mean(axis = 0)
x_std = x.std(axis = 0)
norm = (x - x_mean) / x_std
x = norm

[[ 8.  1.]
 [ 1.  0.]
 [ 8. 10.]
 [ 2.  1.]
 [ 8.  8.]
 [ 5.  7.]]


In [41]:
print(x)
x_mean = x.mean(axis=0)
x_std = x.std(axis=0)
# Assert mean
assert np.abs(np.max(x_mean)) < 10**-6
# Assert standard deviation
assert np.abs(np.max(x_std-1)) < 10**-6

[[ 0.91168461 -0.88662069]
 [-1.48148749 -1.13994089]
 [ 0.91168461  1.39326109]
 [-1.13960576 -0.88662069]
 [ 0.91168461  0.88662069]
 [-0.11396058  0.6333005 ]]


In [42]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Part 2: One-hot Encoding

In [43]:
#from keras.utils import to_categorical
def to_categorical(y):
    """ 1-hot encodes a tensor """
    num_classes = np.max(y) - 1
    matrix = np.zeros([num_classes, len(y)], dtype='uint8')
    for i, x in enumerate(y):
        matrix[:, i] = np.eye(num_classes, dtype='uint8')[x]
    return matrix

tensor = to_categorical([3, 1, 0, 2, 1])

IndexError: index 3 is out of bounds for axis 0 with size 2

In [44]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

### Question

Encode the previous tensor into the `x` variable, following a binary representation (`one-hot encoding`).

In [ ]:
# YOUR CODE HERE

In [ ]:
print(x)
# Assert one-hot encoding
assert x.shape == (5, 4)
assert np.array_equal([0,0,0,1], x[0])
assert np.array_equal([0,1,0,0], x[1])
assert np.array_equal([1,0,0,0], x[2])
assert np.array_equal([0,0,1,0], x[3])
assert np.array_equal([0,1,0,0], x[4])

## Part 3: Image Management

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
from sklearn.datasets import load_sample_images
# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [ ]:
# Load samples images
images = np.asarray(load_sample_images().images)
print(f'Number of images: {len(images)}. Images tensor: {images.shape}')

first_image = images[0]
# Display first image
plt.imshow(first_image)

# Print details about first image
print(f'First image: {first_image.shape}')

### Question

Store in variables respectively named `rgb_values_topleft` and `rgb_values_bottomright` the RGB values of the top-left and bottom-right pixels of the first image.

In [ ]:
# YOUR CODE HERE

In [ ]:
print(f'Top-left pixel: {rgb_values_topleft}')
assert rgb_values_topleft.shape == (3,)
print(f'Bottom-right pixel: {rgb_values_bottomright}')
assert rgb_values_bottomright.shape == (3,)

### Question

Reshape the previous `images` tensor into a 2D tensor.

In [ ]:
# YOUR CODE HERE

In [ ]:
# Assert new tensor dimensions
assert images.shape == (2, 819840)
# Assert RGB values of top-left in first image
assert np.array_equal(rgb_values_topleft, images[0,:3])
# Assert RGB values of bottom-right pixel in first image
assert np.array_equal(rgb_values_bottomright, images[0,819837:])